  language: python
  
  os:
    - linux
    - ubuntu
    

  install:
  - pip install -r requirements.txt
  
  script:
    - pytest


  notifications:
    email:
      recipients:
      - braun@vsp.tu-berlin.de
      on_success: always
      on_failure: always